### PR TITLE
Fix Ruby3 compatibility issue with Procs

### LINKED ISSUE #158: Proc shortcuts do not work with Ruby 3.0
## Expected Behavior
When 'aliasing' an attribute to a different name, you can pass the original as a proc shortcut, like so:

```ruby
class MovieSerializer
  include JSONAPI::Serializer

  attribute :released_in_year, &:year
end
```

## Actual Behavior
Using Ruby 3.0.0, however, this results in the following error:
```
ArgumentError:
wrong number of arguments (given 1, expected 0)
 # ./lib/fast_jsonapi/helpers.rb:10:in `call_proc'
 # ./lib/fast_jsonapi/scalar.rb:14:in `serialize'
 # ./lib/fast_jsonapi/serialization_core.rb:49:in `block in attributes_hash'
```
This appears to be caused by a change (or bug) in the way the parameters for Proc created by `Symbol.to_proc` are defined. 
In Ruby 3.0, the length of the parameters array returned for a Proc created using the `&:foo` shortcut is now 2, though in reality the Proc only requires to be passed the receiver object (i.e., it doesn't really take any parameters). Looks like the helper code needs to be a bit smarter about how it counts Proc parameters since it can't rely on just the length of that Array. I'll fiddle with it and submit a pull request.

## Steps to Reproduce the Problem
The existing test fixtures don't currently include an example of the proc shortcut, but by simply adding:
```
attribute :released_in_year, &:year
```
to the `MovieSerializer` fixture and running rspec using Ruby 3.0.0 will demonstrate the problem.

## Specifications

  - Version: 2.1.0
  - Ruby version: 3.0.0

### PR DESCRIPTION
**Pull request by rmlockerd**
## What is the current behavior?

Fixes #158 (Shorthand Proc don't work with Ruby 3.0)

The Proc helper code uses the length of `Proc.parameters` to determine how many parameters the Proc/lambda accepts. However, lambdas created from a symbol (`&:foo`) take an unknown number of parameters, though they always take at least one, which is the 'receiver' object (i.e., an object that responds to the symbol).

In Ruby < 3.0 `Proc.parameters` for these lambdas always had a length of one with an unnamed parameter of type `rest`:
```
>> :foo.to_proc.parameters
=> [[:rest]]
```
This sort of worked since the proc helper just stuffed the record into the first parameter as the receiver. In Ruby 3.0, though, `Proc.parameters` now contains two unnamed elements:
```
>> :foo.to_proc.parameters
=> [[:req], [:rest]]
```
I assume that the change is to reflect that these lambdas do require at least the receiver. There's no elegant way to catch this case, so I tweaked the proc helper to detect when there is an unnamed parameter in the first position and treat it as only requiring the record. I also added an example of this case in the fixtures.
## Checklist

Please make sure the following requirements are complete:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes /
  features)
- [x] All automated checks pass (CI/CD)

### CODE REVIEW

File: lib/fast_jsonapi/helpers.rb [hunk 1]
```diff
@@ -6,7 +6,15 @@ class << self
...
-      proc.call(*params.take(proc.parameters.length))
+      # The parameters array for a lambda created from a symbol (&:foo) differs
+      # from explictly defined procs/lambdas, so we can't deduce the number of
+      # parameters from the array length. Instead, look for an unnamed
+      # parameter in the first position just pass the record as the receiver obj.
+      if proc.parameters.positive? && !proc.parameters.empty?
+        proc.call(params.first)
+      else
+        proc.call(*params.take(proc.parameters.length))
+      end
```
Comment (ziggythehamster) [inline lib/fast_jsonapi/helpers.rb:17]: Hope you don't mind the rando leaving a comment here but I don't think `.empty?` is a correct check. On Ruby 2.7, this is what I see:

```
irb(main):056:0> :foo.to_proc.parameters.empty?
=> false
irb(main):057:0> -> {}.parameters.empty?
=> true
irb(main):058:0> ->(a) {}.parameters.empty?
=> false
```

There's also not a `positive?` method on `parameters`. I think it'd be better to say `if proc.arity.negative?` since it appears that the arity of a pretzel-operator/`to_proc` proc is -1

Comment (ziggythehamster) [reply lib/fast_jsonapi/helpers.rb:17]: Here's the doc for `arity`: https://ruby-doc.org/core-3.0.0/Proc.html#method-i-arity

Comment (ziggythehamster) [reply lib/fast_jsonapi/helpers.rb:17]: Even better, I just looked at the CRuby source.

For symbol block types, [the min arity is 1 and the max arity is UNLIMITED_ARGUMENTS which is -1](https://github.com/ruby/ruby/blob/8da7f4abc779c6549833d718336d75aac98494b8/proc.c#L1081). The min/max arity is then taken by [rb_proc_arity](https://github.com/ruby/ruby/blob/8da7f4abc779c6549833d718336d75aac98494b8/proc.c#L1123) and this complicatedly written logic runs:

```c
return (proc->is_lambda ? min == max : max != UNLIMITED_ARGUMENTS) ? min : -min-1;
```

symbol blocks are lambdas, but min != max, so this becomes:


```c
return(false ? min : -min-1)
```

So I'd expect on Ruby 3.0 that your arity would be -2 and my arity is -1, so `.arity.negative?` is compatible for both.

Comment (rmlockerd) [reply lib/fast_jsonapi/helpers.rb:17]: Excellent, thanks! I couldn't quite fathom how the `.arity` logic worked so I didn't quite trust just checking for negative arity there. I'll simplify the pull request.

Comment (ziggythehamster) [reply lib/fast_jsonapi/helpers.rb:18]: Me neither, and honestly I'm not sure why they wrote it this way. `-1` would mean "no required arguments and unlimited rest arguments", where `-2` means "one required argument and unlimited rest arguments", which is really counterintuitive. From that perspective, `-2` is actually the correct value because symbol block types require one argument (the receiver), and `-1` is wrong, but it probably shouldn't require reviewing the C source to figure that out.

The right answer would be to make a proc method like `symbol?` for this special case (because this Proc is a special case everywhere anyways in C land - it argument errors by saying "no receiver given" rather than "wrong number of arguments", for instance).

As it stands, the only way I can see to tell this specific situation is to parse `to_s`:

```c
      case block_type_symbol:
	rb_str_catf(str, "%p(&%+"PRIsVALUE")", (void *)self, block->as.symbol);
	break;
```

```irb
irb(main):075:0> :testing.to_proc.to_s
=> "#<Proc:0x00005568af9c9600(&:testing)>"
```

Comment (rmlockerd) [reply lib/fast_jsonapi/helpers.rb:18]: This particular case here is pretty specific: on the invoker side there's only a max of two parameters available to send: 

1. The object being serialized
2. The `params` hash

So, there's really no reason for anyone to muck around with splatted parameters in their proc/lambda. I'm not too fussed about having it detect any negative arity (i.e., unlimited parameters) and just pass the object being serialized. That works for the pretzel-operator lambda for both 2.x and 3, and doesn't really detract from any other sensible case.

**Comment by stas** [comment]
@rmlockerd @ziggythehamster apologies here, I'm a bit late to the party. Is this ready to be merged, I can still see an open discussion from @ziggythehamster 

Thank you! :bow:

**Comment by rmlockerd** [comment]
> @rmlockerd @ziggythehamster apologies here, I'm a bit late to the party. Is this ready to be merged, I can still see an open discussion from @ziggythehamster
> 
> Thank you! 🙇

Sorry, I neglected to resolve the discussion, but I think we're done. The last commit provides changes to reflect the feedback on the approach. Note that the CI/CD tests are failing because the version of rubocop has updated and it is flagging some issues in unrelated code.

**Comment by stas** [comment]
@rmlockerd sweet! I'll fix the CI and get things on :)
