### PR TITLE
Prevent incorrect fieldset caching

### LINKED ISSUE #90: Fields option is cached
Suppose we have the following serializer

```rb
class UserSerializer
  include FastJsonapi::ObjectSerializer
  cache_options store: Rails.cache, namespace: 'fast-jsonapi', expires_in: 12.hours

  attributes :username, :email, :firstname, :lastname
end
```

If we initialize the serializer with `fields` option, the resulting filtered JSON is cached

```rb
UserSerializer.new(user, fields: { user: %i[first_name last_name] }).serializable_hash
# {:data=>
#  {:id=>"1",
#   :type=>:user,
#   :attributes=>{:first_name=>"John", :last_name=>"Doe"},
#   :relationships=>{}}}
```

## Expected Behavior

Subsequent instances of to `UserSerializer` should respect their own `fields` option

```rb
UserSerializer.new(user).serializable_hash
# {:data=>
#  {:id=>"1",
#   :type=>:user,
#   :attributes=>
#    {:username=>"john.doe.1",
#     :first_name=>"John",
#     :last_name=>"Doe"
#     :email=>"johndoe@gmail.com"},
#   :relationships=>{}}}

UserSerializer.new(user, fields: { user: %i[email] }).serializable_hash
# {:data=>
#  {:id=>"1",
#   :type=>:user,
#   :attributes=>{:email=>"johndoe@gmail.com"},
#   :relationships=>{}}}
```

## Actual Behavior

All subsequent calls to the serializer will return with first sparse fieldsets regardless of specified `fields` option until the cache is cleared.

```rb
UserSerializer.new(user).serializable_hash
# {:data=>
#  {:id=>"1",
#   :type=>:user,
#   :attributes=>{:first_name=>"John", :last_name=>"Doe"},
#   :relationships=>{}}}

UserSerializer.new(user, fields: { user: %i[email] }).serializable_hash
# {:data=>
#  {:id=>"1",
#   :type=>:user,
#   :attributes=>{:first_name=>"John", :last_name=>"Doe"},
#   :relationships=>{}}}
```

## Specifications

  - Version: 1.7.2
  - Ruby version: 2.6.5

---

Since `fields` is specify for each instance of the serializer, it should probably be applied after data is stored in the cache so each instance can filter fields independent of each other.

Alternatively, if the record `cache_key` can be dynamically generated based on the serializer instance options, the `fields` can be included as part of  `cache_key`.

### PR DESCRIPTION
**Pull request by wheatevo**
This change alters the cache namespace prior to retrieving cached record
data to ensure that different fieldsets are given different cache keys.

Previously, all cache keys for the same record would be specified
identically, leading to a situation where the fieldset would be ignored
if record caching is enabled.

Fixes #90.

## What is the current behavior?
See #90 

## What is the new behavior?

The cache namespace is now altered prior to gathering cached entries with specific fieldsets. If a fieldset is specified, `"-fieldset:#{fieldset.join('_')"` will be appended to the cache namespace.

For example, if the fields `a`, `b`, and `c` were requested and the main namespace is `ns`, the generated namespace would be `ns-fieldset:a_b_c`.

## Checklist

Please make sure the following requirements are complete:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] All automated checks pass (CI/CD)

### CODE REVIEW

File: lib/fast_jsonapi/serialization_core.rb [hunk 1]
```diff
@@ -86,6 +86,24 @@ def record_hash(record, fieldset, includes_list, params = {})
...
+      # If no fieldset is specified, the namespace will be unaltered.
+      #
+      # @param [Hash] options cache options hash
+      # @param [Array, nil] fieldset fieldset array or nil if unspecified
+      #
+      # @return [Hash] processed options hash
+      #
+      def process_cache_options(options, fieldset)
+        options = options ? options.dup : {}
+        options[:namespace] = "#{options[:namespace]}-fieldset:#{fieldset.join('_')}" if fieldset
```
Comment (stas) [inline lib/fast_jsonapi/serialization_core.rb:103]: @wheatevo do you mind if we make this pretty please? :upside_down_face: 

First of all, if there's no namespace, we'll end up with something like `-fieldset:....<MODEL NAME>/id` [see cache key docs for more context](https://devdocs.io/rails~6.0/activerecord/integration#method-i-cache_key).

I'd like us to make sure that the namespace carries some context. Consider using the `jsonapi-<FIELDSETS VERSION>` if there's no namespace. If there's one available, let's just add the `-<FIELDSETS VERSION>` to it.

Another note here, is that I'm concerned about the size of this key. The caching stores seem to have a limit on the size of the final key, and it might be a better alternative to take care of it before we send it over to the caching store. Consider the approach [AS took on the memcache store](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/cache/mem_cache_store.rb#L162).

Let me know what you think?!

File: CHANGELOG.md [hunk 2]
```diff
@@ -8,6 +8,9 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 ### Changed
 - Remove `ObjectSerializer#serialized_json` (#91)
 
+### Fixed
+- Ensure caching correctly incorporates fieldset information into the cache key to prevent incorrect cache collisions (#90)
```
Comment (stas) [inline CHANGELOG.md:12]: Let's update the part with `collisions` here as well. See below...

File: lib/fast_jsonapi/serialization_core.rb (hunk 1 above)
Comment (wheatevo) [reply lib/fast_jsonapi/serialization_core.rb:103]: Thank you for the quick review! I was not entirely happy with this solution so I appreciate your feedback.

I will make the requested changes and push up a new commit.

File: CHANGELOG.md (hunk 2 above)
Comment (wheatevo) [reply CHANGELOG.md]: Request change has been made.

File: lib/fast_jsonapi/serialization_core.rb (hunk 1 above)
Comment (wheatevo) [reply lib/fast_jsonapi/serialization_core.rb]: Requested change has been made.

I ended up using SHA1 instead of MD5 to preserve FIPS compatibility. This should probably use `ActiveSupport::Digest` (https://github.com/rails/rails/pull/31289) if the active_support dependency is bumped in the future.

File: lib/fast_jsonapi/serialization_core.rb [hunk 3]
```diff
@@ -86,6 +86,24 @@ def record_hash(record, fieldset, includes_list, params = {})
         record_hash
       end
 
+      #
+      # It modifies cache options to prevent cache key collisions.
```
[the remark this answers is not in the document]
Comment (wheatevo) [reply lib/fast_jsonapi/serialization_core.rb]: Requested change has been made.

File: lib/fast_jsonapi/serialization_core.rb [hunk 4]
```diff
@@ -86,6 +86,24 @@ def record_hash(record, fieldset, includes_list, params = {})
...
+      # If a fieldset is specified, it modifies the namespace to include the fields from the fieldset.
+      #
+      # If no fieldset is specified, the namespace will be unaltered.
+      #
+      # @param [Hash] options cache options hash
+      # @param [Array, nil] fieldset fieldset array or nil if unspecified
+      #
+      # @return [Hash] processed options hash
+      #
+      def process_cache_options(options, fieldset)
```
[the remark this answers is not in the document]
Comment (wheatevo) [reply lib/fast_jsonapi/serialization_core.rb]: Requested change has been made.

**Comment by wheatevo** [comment]
All of the current suggestions have been implemented, please let me know if there are any other pieces that should be changed.

**Comment by stas** [comment]
Thanks a lot @wheatevo :bow: :star_struck: 

I'll prepare a release with these.
